import re
import unittest
import pandas as pd

EXTRACTOR_NAME = 'ext-mem-rw-dump'
sample_file = """#
# Memory Access Trace Generated By Pin
#
0x00007ffd37cd1493: W 0x000000361957ec40  1                0x1
0x00007ffd37cd1497: R 0x0000003619691060  8       0x3619690000
0x00007ffd37cd14a0: R 0x0000003619690090  8                  0
0x00007ffd37cd14ac: R 0x000000007ffe0384  1                  0
0x00007ffd37cd14b5: R 0x000000361957ec40  1                0x1
0x00007ffd37cd14bf: R 0x000000361957ec80  8      0x190c9617040
0x00007ffd37cd14c8: R 0x000000361957ec50  8                  0
"""

def parse_line(str):
	regex = r'(\w+): (W|R) (\w+) +(\d) +(\w+)'
	match = re.match(regex, str)
	if match:
		ins_addr = match.group(1)
		rw = match.group(2)
		tgt_addr = match.group(3)
		return (int(ins_addr, 16), rw, int(tgt_addr, 16))
	return None	

def get_df(stats):
	idx = [s[0] for s in stats]
	mem_access = {
		'RW' : pd.Series([s[1] for s in stats], index=idx),
		'TGT' :pd.Series([s[2] for s in stats], index=idx)
	}

	df = pd.DataFrame(mem_access)
	return df

def stub():
	stats = []
	for line in sample_file.split('\n'):
		p = parse_line(line)
		if p is not None:
			stats.append(p)

	return get_df(stats)


if __name__ == '__main__':
	print stub()